export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const UNSUCCESSFUL_LOGIN = 'UNSUCCESSFUL_LOGIN';
export const LOG_OUT = 'LOG_OUT';
export const STORE_INFO = 'STORE_INFO';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_LOADED_ERROR = 'CATEGORIES_LOADED_ERROR';
